services:
  nestjs:
    build: containers/nestjs
    image: nestjs
    container_name: nestjs
    env_file: .env
    init: true # Prevents waiting on 10s timeout on shutdown
    restart: on-failure
    ports:
      - "4242:4242"
    volumes:
      - ./containers/nestjs/:/nestjs/code/
    depends_on:
      - vuejs # Prevents npm ci timeout

  vuejs:
    build: containers/vuejs
    image: vuejs
    container_name: vuejs
    env_file: .env
    init: true # Prevents waiting on 10s timeout on shutdown
    restart: on-failure
    ports:
      - 2424:2424
    volumes:
      - ./containers/vuejs/:/vuejs/code/
